version: "3.9"

services:
  db:
    image: mysql
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Esmun
      MYSQL_DATABASE: foodapp
    cap_add:
      - SYS_NICE
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    container_name: backend
    command: ["./wait-for-it.sh", "db:3306", "--", "npm", "start"]
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    container_name: frontend
    depends_on:
      - backend
